spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: info
    com.kyle: debug
  file: log/blog-dev.log

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.kyle.pojo